# Generated by Django 4.1.5 on 2023-01-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_rename_phonenumber_user_phonenumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(blank=True, default="email", max_length=50),
        ),
    ]
