# Generated by Django 4.1.5 on 2023-01-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_user_auth_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(blank=True, default="google", max_length=50),
        ),
    ]
