# Generated by Django 4.1.5 on 2023-01-04 00:16

import annonce.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Adresse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Annonce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("primaire", "primaire"),
                            ("collège", "collège"),
                            ("lycée ", "lycée "),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "modalite",
                    models.CharField(
                        choices=[("offline ", "offline "), ("online ", "online ")],
                        max_length=8,
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=300)),
                ("tarif", models.CharField(max_length=30)),
                ("wilaya", models.CharField(max_length=50)),
                ("Commune", models.CharField(max_length=50)),
                ("slug", models.SlugField(max_length=250, unique=True)),
                ("published", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={"ordering": ("-published",),},
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Wilaya",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("code", models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "upload",
                    models.ImageField(upload_to=annonce.models.user_directory_path),
                ),
                (
                    "annonce",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="annonce.annonce",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Commune",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "wilaya",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="annonce.wilaya"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="annonce",
            name="Theme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="annonce.theme"
            ),
        ),
        migrations.AddField(
            model_name="annonce",
            name="adresse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="annonce.adresse"
            ),
        ),
        migrations.AddField(
            model_name="annonce",
            name="annoncer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annonces",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="annonce",
            name="bookmarks",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="bookmark",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="adresse",
            name="Commune",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="annonce.commune"
            ),
        ),
    ]
