# Generated by Django 4.1.4 on 2022-12-27 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Annonce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("primaire", "primaire"),
                            ("collège", "collège"),
                            ("lycée ", "lycée "),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "modalite",
                    models.CharField(
                        choices=[("offline ", "offline "), ("online ", "online ")],
                        max_length=8,
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=300)),
                ("tarif", models.CharField(max_length=30)),
                ("wilaya", models.CharField(max_length=50)),
                ("Commune", models.CharField(max_length=50)),
                ("adresse", models.CharField(blank=True, max_length=50)),
                ("slug", models.SlugField(max_length=250, unique=True)),
                ("published", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "Theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="annonce.theme"
                    ),
                ),
                (
                    "annoncer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annonces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ("-published",),},
        ),
    ]
