# Generated by Django 4.1.5 on 2023-01-24 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("annonce", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="annonce", name="Commune",),
        migrations.RemoveField(model_name="annonce", name="bookmarks",),
        migrations.RemoveField(model_name="annonce", name="wilaya",),
        migrations.AddField(
            model_name="adresse",
            name="wilaya",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="adresse",
            name="Commune",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="annonce",
            name="Theme",
            field=models.CharField(
                choices=[("math ", "math "), ("science ", "science ")], max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="annonce",
            name="slug",
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name="photo",
            name="annonce",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="annonce.annonce",
            ),
        ),
        migrations.DeleteModel(name="Commune",),
        migrations.DeleteModel(name="Theme",),
        migrations.DeleteModel(name="Wilaya",),
        migrations.AddField(
            model_name="bookmark",
            name="Annonce",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="annonce.annonce"
            ),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
