# Generated by Django 4.1.5 on 2023-01-26 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("annonce", "0002_bookmark_remove_annonce_commune_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="annonce", old_name="Theme", new_name="theme",
        ),
        migrations.RemoveField(model_name="annonce", name="slug",),
        migrations.AlterField(
            model_name="annonce",
            name="adresse",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="annonce.adresse",
            ),
        ),
    ]
