# Generated by Django 4.1.5 on 2023-01-26 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("annonce", "0004_alter_annonce_category_alter_annonce_modalite_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annonce",
            name="adresse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="annonce.adresse",
            ),
        ),
    ]
