# Generated by Django 4.1.5 on 2023-01-29 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annonce", "0007_conversation_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annonce", name="title", field=models.CharField(max_length=100),
        ),
    ]
