# Generated by Django 4.1.5 on 2023-01-30 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("annonce", "0008_alter_annonce_title"),
    ]

    operations = [
        migrations.RemoveField(model_name="annonce", name="adresse",),
        migrations.AddField(
            model_name="adresse",
            name="annonce",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adresse",
                to="annonce.annonce",
            ),
        ),
        migrations.AlterField(
            model_name="annonce",
            name="annoncer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annoncer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
