# Generated by Django 4.1.5 on 2023-01-30 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annonce", "0009_remove_annonce_adresse_adresse_annonce_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="adresse", old_name="Commune", new_name="commune",
        ),
    ]
