# Generated by Django 4.1.5 on 2023-01-30 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("annonce", "0010_rename_commune_adresse_commune"),
    ]

    operations = [
        migrations.RemoveField(model_name="adresse", name="annonce",),
        migrations.AddField(
            model_name="annonce",
            name="adresse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="annonce.adresse",
            ),
        ),
    ]
