# Generated by Django 4.1.5 on 2023-01-30 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("annonce", "0011_remove_adresse_annonce_annonce_adresse"),
    ]

    operations = [
        migrations.RemoveField(model_name="annonce", name="adresse",),
        migrations.AddField(
            model_name="adresse",
            name="annonce",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adresse",
                to="annonce.annonce",
            ),
        ),
    ]
