# Generated by Django 4.1.5 on 2023-01-30 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("annonce", "0012_remove_annonce_adresse_adresse_annonce"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adresse",
            name="annonce",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="add",
                to="annonce.annonce",
            ),
        ),
    ]
