# Generated by Django 4.1.5 on 2023-01-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annonce", "0014_rename_commune_adresse_commune_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="annonce",
            name="year",
            field=models.CharField(
                choices=[
                    ("1AP", "1AP"),
                    ("2AP", "2AP"),
                    ("3AP", "3AP"),
                    ("4AP", "4AP"),
                    ("5AP", "5AP"),
                    ("1AM", "1AM"),
                    ("2AM", "2AM"),
                    ("3AM", "3AM"),
                    ("4AM", "4AM"),
                    ("1AS", "1AS"),
                    ("2AS", "2AS"),
                    ("3AS", "3AS"),
                ],
                max_length=7,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="annonce",
            name="category",
            field=models.CharField(
                choices=[
                    ("primaire", "primaire"),
                    ("college", "college"),
                    ("lycee", "lycee"),
                    ("Primary School", "Primary School"),
                    ("Middle School", "Middle School"),
                    ("Secondary School", "Secondary School"),
                ],
                max_length=40,
            ),
        ),
    ]
